.PHONY: test
test: lint
	go test -count=1 -timeout=30s ./...
	TEST_RACE=1 go test -timeout=90s -race -count=1 ./paxos/...
	TEST_RACE=1 go test -timeout=90s -race -count=1 ./cond/...
	TEST_RACE=1 go test -timeout=90s -race -count=1 ./async/...
	TEST_RACE=1 go test -timeout=90s -race -count=1 ./testutil/...

.PHONY: lint
lint:
	go fmt ./...
	go vet ./...
	go mod tidy
